version: '3.9'

services:
  app:
    build: .
    container_name: capital-bot
    env_file:
      - .env
    depends_on:
      - redis
    restart: always

  redis:
    image: redis:latest
    container_name: redis_container
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: always

volumes:
  redis_data:
